---
- name: create tls directory structure
  sudo: yes
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0700
  tags:
    - nginx

- name: deploy tls files
  sudo: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: u=r
  with_items:
    - src: ssl/certs/nginx.cert.pem
      dest: /etc/nginx/ssl/nginx.cert
    - src: ssl/private/nginx.key.pem
      dest: /etc/nginx/ssl/nginx.key
  tags:
    - nginx
