---
- name: add mesosphere repository
  sudo: yes
  yum:
    name:  http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm 
    state: present

- name: install marathon package
  sudo: yes
  yum:
    name: marathon 
    state: present

- name: enable and start marathon
  sudo: yes
  service:
    enabled: yes
    name: marathon
    state: started

