---
- name: register distributive tests with consul
  sudo: yes
  copy:
    src: distributive-service-consul.json
    dest: /etc/consul
  notify:
    - reload consul
  tags:
    - consul

- name: copy distributive consul test
  sudo: yes
  copy:
    src: distributive-checklist-consul.json
    dest: /usr/share/distributive/consul.json

- name: run distributive consul test
  sudo: yes
  command: /usr/bin/distributive -f /usr/share/distributive/consul.json
  tags:
    - consul
