---
- name: Generate Consul systemd unit
  sudo: yes
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
  tags: consul,consul-generate-unit
  notify:
    - Restart Consul
    - Wait for Consul ports

- name: Enable Consul
  sudo: yes
  service:
    name: consul
    enabled: yes
  tags: consul,consul-enable-unit
