---
- name: install consul rpms
  sudo: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - https://bintray.com/artifact/download/asteris/rpm/consul-0.5.0-2.el7.centos.x86_64.rpm
    - https://bintray.com/artifact/download/asteris/rpm/consul-ui-0.5.0-2.el7.centos.x86_64.rpm

- name: create TLS struture
  sudo: true
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default(0700) }}"
  with_items:
    - path: /etc/consul/ssl
  when: consul_enable_tls == true
  tags:
    - consul

- name: copy tls files
  sudo: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0400
  with_items:
    - src: ca.cert
      dest: /etc/consul/ssl
    - src: consul.cert
      dest: /etc/consul/ssl
    - src: consul.key
      dest: /etc/consul/ssl
  when: consul_enable_tls == true
  tags:
    - consul

- name: configure consul
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: consul.sysconfig.j2
      dest: /etc/sysconfig/consul
    - src: consul.json.j2
      dest: /etc/consul/consul.json
    - src: consul.nginx.j2
      dest: /etc/nginx/conf.d/consul.conf
  notify:
    - reload consul
  tags:
    - consul
