---
- name: run consul container
  sudo: yes
  docker: >
    name=consul
    image=progrium/consul
    state=running
    hostname={{ inventory_hostname }}
    ports=8300:8300,8301:8301,8301:8301/udp,8302:8302,8302:8302/udp,8400:8400,8500:8500,8600:53/udp
    command="{% if consul_is_server is defined %}-server -bootstrap-expect {{ consul_bootstrap_expect }}{% endif %} -advertise {{ ansible_eth0.ipv4.address }} -rejoin -retry-join {{ consul_retry_join}}"
