---
- name: install consul
  sudo: yes
  yum:
    name: "https://bintray.com/artifact/download/ciscocloud/rpm/consul-0.5.0-2.el7.centos.x86_64.rpm"
    state: present
  notify:
    - enable consul
  tags: 
    - consul

- name: install consul-ui
  sudo: yes
  yum:
    name: "https://bintray.com/artifact/download/ciscocloud/rpm/consul-ui-0.5.0-2.el7.centos.x86_64.rpm"
    state: present
  when: consul_is_server 
  notify:
    - enable consul
  tags: 
    - consul

- name: deploy tls files
  sudo: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('consul') }}"
    mode: "{{ item.mode | default(0400) }}"
  with_items:
    - src: ssl/cacert.pem
      dest: /etc/consul/ssl/{{ consul_ca_file }}
    - src: ssl/certs/consul.cert.pem
      dest: /etc/consul/ssl/{{ consul_cert_file }}
    - src: ssl/private/consul.key.pem
      dest: /etc/consul/ssl/{{ consul_key_file }}
    - src: consul.nginx
      dest: /etc/consul
      mode: u=rw,g=r,o=r
  tags:
    - consul

- name: configure consul
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: consul.sysconfig.j2
      dest: /etc/sysconfig/consul
    - src: consul.json.j2
      dest: /etc/consul/consul.json
    - src: consul_nginx.service.j2
      dest: /usr/lib/systemd/system/nginx-consul.service
  notify:
    - reload consul
    - restart nginx-consul
  tags:
    - consul

- name: configure consul acl policy
  sudo: yes
  template:
    src: acl.json.j2
    dest: /etc/consul/acl.json
  when:
    - consul_acl_master_token != ""
  notify:
    - reload consul
  tags:
    - consul

- name: enable consul
  sudo: yes
  service:
    name: consul
    enabled: yes
    state: started
  tags:
    - consul

- name: configure nginx
  sudo: yes
  command: curl -X PUT -d @/etc/consul/consul.nginx localhost:8500/v1/kv/service/nginx/templates/consul?token="{{ consul_acl_master_token }}"
  tags:
    - consul

- name: enable nginx-consul
  sudo: yes
  service:
    name: nginx-consul
    enabled: yes
    state: started
  notify:
    - restart nginx-consul
  tags:
    - consul
