---
- name: create directories
  sudo: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - /data
    - /data/ui
    - /etc/consul.d
  tags:
    - consul

- name: install unzip
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip
  tags:
    - consul

- name: download consul
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: 0640
  with_items:
    - { 
        url: 'https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip',
        dest: '/tmp/consul.zip' 
      }
    - {
        url: 'https://dl.bintray.com/mitchellh/consul/0.5.0_web_ui.zip',
        dest: '/tmp/ui.zip'
      }
  tags:
    - consul

- name: unzip consul
  sudo: true
  unarchive:
    copy: false
    creates: "{{ item.creates }}"
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items:
    - {
        creates: '/bin/consul',
        src: '/tmp/consul.zip',
        dest: '/bin',
        mode: '+x'
      }
    - {
        creates: '/data/ui/dist/index.html',
        src: '/tmp/ui.zip',
        dest: '/data/ui'
      }
  tags:
    - consul

- name: uninstall unzip
  sudo: true
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - unzip
  tags:
    - consul

- name: cleanup download
  sudo: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '/tmp/consul.zip'
    - '/tmp/ui.zip'
  tags:
    - consul


- name: configure consul
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: consul.service.j2
      dest: /usr/lib/systemd/system/consul.service
    - src: consul.json.j2
      dest: /etc/consul.d/consul.json
  notify:
    - reload consul
  tags:
    - consul
