---
- name: Download conntrack
  sudo: yes
  yum:
    name: conntrack
    state: latest

- name: Generate Consul systemd unit
  sudo: yes
  template:
    src: consul.service.j2
    dest: /usr/lib/systemd/system/consul.service
  tags:
    - consul
    - consul-generate-unit
  notify:
    - Restart Consul
