---
- name: deploy nginx template
  sudo: yes
  copy:
    src: consul.nginx
    dest: /etc/nginx/templates
  notify:
    - reload nginx
  tags:
    - consul

- name: enable nginx-consul
  sudo: yes
  service:
    name: nginx-consul
    enabled: yes
    state: started
  notify:
    - restart nginx-consul
  tags:
    - consul
