---
- name: delete agent acl
  run_once: yes
  command: curl -X PUT localhost:8500/v1/acl/destroy/{{ consul_agent_acl_token }}?token={{ consul_acl_master_token }}
  when: consul_agent_acl_token is defined
  register: command_result
  notify:
    - restart consul
  tags:
    - consul
