---
- name: install collectd
  sudo: yes
  yum:
    name: collectd
    state: present
  tags:
    - collectd
    - bootstrap

- name: configure collectd
  sudo: yes
  template:
    src: collectd.conf.j2
    dest: /etc/collectd.conf
  notify:
    - restart collectd
  tags:
    - collectd

- name: create collectd config directory
  sudo: yes
  file:
    path: /etc/collectd.d
    state: directory
    mode: 0755
  tags:
    - collectd

- name: create collectd plugin directory
  sudo: yes
  file:
    path: /usr/share/collectd/plugins
    state: directory
    mode: 0755
  tags:
  - collectd

- name: enable collectd
  sudo: yes
  service:
    name: collectd
    enabled: yes
    state: started
  tags:
    - collectd


