---
- include: playbooks/provision-hosts.yml

- hosts: all
  roles:
    - common
    - docker
    - dnsmasq
    - cadvisor
    - logspout

- hosts: consul_client
  roles:
    - consul

- hosts: consul_server:&dc1
  serial: 1
  roles:
    - consul

- hosts: consul_server:&dc2
  serial: 1
  roles:
    - consul

- include: playbooks/consul-join-wan.yml

- hosts: all
  gather_facts: no
  roles:
    - registrator

- hosts: app
  gather_facts: no
  roles:
    - app

- hosts: load_balancer
  gather_facts: no
  roles:
    - load-balancer
