---
- include: playbooks/provision-hosts.yml

- hosts: all
  roles:
    - common
    - docker
    - dnsmasq

- hosts: consul_client
  gather_facts: no
  roles:
    - consul

- hosts: consul_server:&dc1
  gather_facts: no
  serial: 1
  roles:
    - consul

- hosts: consul_server:&dc2
  gather_facts: no
  serial: 1
  roles:
    - consul

- include: playbooks/consul-join-wan.yml

- hosts: all
  gather_facts: no
  roles:
    - registrator

