---
- include: playbooks/provision-hosts.yml

- hosts: all
  roles:
    - { role: common, tags: common }
    - { role: docker, tags: docker }

- hosts: all:!consul_servers
  roles:
    - { role: consul, tags: consul }

- hosts: consul_servers
  serial: 1
  roles:
    - { role: consul, tags: consul }

- hosts: all
  gather_facts: no
  roles:
    - { role: registrator, tags: registrator }

- hosts: app_servers
  gather_facts: no
  roles:
    - { role: hello-world, tags: app }

- hosts: load_balancers
  gather_facts: no
  roles:
    - { role: nginx, tags: lb }

- include: playbooks/upgrade-packages.yml
