---
- include: playbooks/provision-hosts.yml

- hosts: all
  roles:
    - role: common
      tags: ['common']

    - role: docker
      tags: ['docker']

    - role: dnsmasq
      tags: ['dnsmasq']

    - role: logspout
      tags: ['logspout']

- hosts: consul_client
  roles:
    - role: consul
      tags: ['consul','consul-client']

- hosts: consul_server:&dc1
  serial: 1
  roles:
    - role: consul
      tags: ['consul','consul-server']

- hosts: consul_server:&dc2
  serial: 1
  roles:
    - role: consul
      tags: ['consul','consul-server']

- include: playbooks/consul-join-wan.yml

- hosts: all
  gather_facts: no
  roles:
    - role: registrator
      tags: ['registrator']

- hosts: app
  gather_facts: no
  roles:
    - role: app
      tags: ['app']

- hosts: load_balancer
  gather_facts: no
  roles:
    - role: load-balancer
      tags: [load-balancer]
