---
- hosts: all
  roles:
    - common

- hosts: all
  gather_facts: no
  roles:
    - consul-template

- hosts: all
  gather_facts: no
  roles:
    - docker

- hosts: all
  gather_facts: no
  roles:
    - dnsmasq

- hosts: all
  gather_facts: no
  roles:
    - nginx

- hosts: all
  gather_facts: no
  roles:
    - consul

- hosts: all
  gather_facts: no
  roles:
    - registrator

- hosts: all
  gather_facts: no
  roles:
    - zookeeper

- hosts: all
  gather_facts: no
  roles:
    - mesos

- hosts: all
  gather_facts: no
  roles:
    - marathon
