---
- name: restart calico
  sudo: yes
  service:
    name: calico
    state: restarted

- name: restart mesos agent
  sudo: yes
  service:
    name: mesos-slave
    state: restarted
  when: mesos-agent-active.rc == 0 and mesos-agent-active.stdout == "active"