---
# some created directories may be redundant, but are kept in case anything else
# changes, and to enable the picking and choosing of components/roles.
- name: create consul configuration directory
  sudo: yes
  file:
    path: /etc/consul
    state: directory
    mode: 0770
  tags:
    - consul
    - distributive
    - logrotate

- name: create symlink to distributive logrotate checklist
  sudo: yes
  file:
    state: link
    src: /usr/share/distributive/logrotate.json
    dest: /etc/distributive.d/logrotate.json
  tags:
    - consul
    - distributive
    - logrotate

- name: register distributive tests with consul
  sudo: yes
  copy:
    src: distributive-logrotate-check.json
    dest: /etc/consul/
  notify:
    - reload consul
  tags:
    - consul
    - distributive
    - logrotate
