---
- name: set logrotate interval to daily
  sudo: yes
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: '^weekly'
    line: "daily"

- name: set logrotate retention period to 7 days
  sudo: yes
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: '^rotate 4'
    line: "rotate 7"

- name: configured mesos logrotate
  sudo: yes
  file:
    src: mesos
    dest: /etc/logrotate.d/mesos
    mode: 644
    owner: root
    group: root

- name: configure docker logrotate
  sudo: yes
  file:
    src: docker
    dest: /etc/logrotate.d/docker
    mode: 644
    owner: root
    group: root
