---
- name: configure leader defaults
  sudo: yes
  template:
    src: master-defaults.j2
    dest: /etc/default/mesos-master
  notify: 
    - restart mesos leader
  tags:
    - mesos

- name: create zookeeper acl
  sudo: yes
  shell: "{{ mesos_zk_acl_cmd }} | docker run --entrypoint /bin/bash asteris/zookeeper"
  notify:
    - restart mesos leader
  tags:
    - mesos

- name: write leader credentials
  sudo: yes
  when: mesos_authenticate_frameworks or mesos_authenticate_followers
  template:
    src: master-credentials.j2
    dest: /etc/mesos/credentials
    mode: 0700
  notify:
    - restart mesos leader
  tags:
    - mesos

- name: delete leader credentials
  sudo: yes
  when: not mesos_authenticate_frameworks and not mesos_authenticate_followers
  file:
    dest: /etc/mesos/credentials
    state: absent
  tags:
    - mesos

- name: generate leader consul service
  sudo: yes
  template:
    src: mesos-leader-consul.j2
    dest: "{{ consul_dir }}/mesos-leader.json"
  notify:
    - reload consul
  tags:
    - consul-service
    - mesos
