---
- name: configure leader defaults
  sudo: yes
  template:
    src: master-defaults.j2
    dest: /etc/default/mesos-master
  notify: 
    - restart mesos leader
  tags:
    - mesos

- name: generate leader consul service
  sudo: yes
  template:
    src: mesos-leader-consul.j2
    dest: /etc/consul/register.d/mesos-leader.json
  notify:
    - register mesos leader with consul
  tags:
    - consul-service
    - mesos
