---
- name: configure leader defaults
  sudo: yes
  template:
    src: master-defaults.j2
    dest: /etc/default/mesos-master
  notify: 
    - restart mesos leader
  tags:
    - mesos

- name: write leader credentials
  sudo: yes
  when: mesos_authenticate_frameworks|bool or mesos_authenticate_followers|bool
  template:
    src: master-credentials.j2
    dest: /etc/mesos/credentials
    mode: 0600
  notify:
    - restart mesos leader
  tags:
    - mesos

- name: delete leader credentials
  sudo: yes
  when: not mesos_authenticate_frameworks|bool and not mesos_authenticate_followers|bool
  file:
    dest: /etc/mesos/credentials
    state: absent
  tags:
    - mesos

- name: generate leader consul service
  sudo: yes
  template:
    src: mesos-leader-consul.j2
    dest: "{{ consul_dir }}/mesos-leader.json"
  notify:
    - reload consul
  tags:
    - consul-service
    - mesos

- name: create zookeeper acl 
  sudo: yes 
  shell: "{{ mesos_zk_acl_cmd }}" 
  notify:
    - restart mesos leader
  when: zk_mesos_user_secret is defined
  run_once: true
  tags:
    - mesos

- name: deploy iptables template
  sudo: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: mesos-leader-consul.cfg
      dest: /etc/consul-template/config.d
    - src: mesos-leader-iptables.tmpl
      dest: /etc/consul-template/templates
  notify:
    - reload consul-template
  tags:
    - mesos

- include: nginx-proxy.yml
