apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: kube-traefik-ingress-controller-config
data:
  traefik.toml: |-
    port = ":80"
    graceTimeOut = 10
    logLevel = "DEBUG"

    [web]
    address = ":8081"
    CertFile = "/etc/pki/mantl/cert"
    KeyFile = "/etc/pki/mantl/key"

    [marathon]
    endpoint = "{{ traefik_marathon_endpoint }}"
    domain = "{{ traefik_marathon_domain }}"
    watch = true
    networkInterface = "{{ ansible_default_ipv4['interface'] }}"
    ExposedByDefault = {{ traefik_marathon_expose_by_default }}

    [kubernetes]
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: kube-traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-traefik-ingress-lb
        name: kube-traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      nodeSelector:
        role: edge
      volumes:
        - name: config-volume
          configMap:
            name: kube-traefik-ingress-controller-config
        - name: cert-volume
          hostPath:
            path: /etc/pki
      containers:
        - image: traefik
          name: kube-traefik-ingress-lb
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              hostPort: 80
            - containerPort: 443
              hostPort: 443
            - containerPort: 8081
              hostPort: 8081
            - containerPort: 8080
              hostPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/traefik
            - name: cert-volume
              mountPath: /etc/pki
          args:
            - -c
            - /etc/traefik/traefik.toml
            - --kubernetes
            - --logLevel=DEBUG
