---
- name: Restart Consul
  sudo: yes
  shell: "{{ item }}"
  with_items:
    - systemctl restart consul
    - systemctl enable consul
    - systemctl daemon-reload
  notify:
    - Wait for Consul ports

- name: Wait for Consul ports
  wait_for:
    port: "{{ item }}"
  with_items:
    - 8500
