---
- name: restart consul
  sudo: yes
  command: systemctl restart consul
  notify:
    - wait for consul to listen

- name: restart nginx-consul
  sudo: yes
  command: systemctl restart nginx-consul
