---
- name: reload consul
  sudo: yes
  command: "{{ item }}"
  with_items:
    - systemctl restart consul
    - systemctl enable consul
    - systemctl daemon-reload
  notify:
    - wait for consul to listen

- name: wait for consul to listen
  wait_for:
    port: 8500
