---
- name: generate systemd unit file
  sudo: yes
  template:
    src: etcd.service.j2
    dest: /usr/lib/systemd/system/etcd.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart etcd
  tags:
    - etcd

- name: install consul check script
  sudo: yes
  template:
    src: consul-check-etcd-member
    dest: /usr/local/bin
    mode: 0755
  when: consul_dc_group is defined
  tags:
    - etcd

- name: register etcd with consul
  sudo: yes
  copy:
    src: etcd-service.json
    dest: /etc/consul
  when: consul_dc_group is defined
  notify:
    - reload consul
  tags:
    - etcd

- name: enable and start etcd
  sudo: yes
  service:
    name: etcd
    enabled: yes
    state: started
  tags:
    - etcd

- include: skydns.yml
  when: dns_setup is defined

- meta: flush_handlers
