---
- name: install glusterfs-fuse
  sudo: yes
  yum:
    name: glusterfs-fuse
    state: present
  tags:
    - glusterfs

- name: create mount points for volumes
  sudo: yes
  file:
    state: directory
    name: "{{ item.mount }}"
    recurse: yes
    mode: 0755
  with_items: glusterfs_volumes
  tags:
    - glusterfs

- name: mount volumes
  sudo: yes
  mount:
    state: mounted
    name: "{{ item.mount }}"
    fstype: glusterfs
    src: "glusterfs.service.{{ consul_dns_domain }}:/{{ item.name }}"
  with_items: glusterfs_volumes
  tags:
    - glusterfs

- name: create consul healthchecks
  sudo: yes
  template:
    src: glusterfs-mounts.json.j2
    dest: /etc/consul/glusterfs-mounts.json
  notify:
    - reload consul
  tags:
    - glusterfs