---
# We disble dnsmasq in systemd so that NetworkManager can control it
- name: disable dnsmasq
  sudo: yes
  command: systemctl disable dnsmasq

- name: restart dnsmasq
  sudo: yes
  command: systemctl restart dnsmasq 
