---
# some created directories may be redundant, but are kept in case anything else
# changes, and to enable the picking and choosing of components/roles.
- name: create consul configuration directory
  sudo: yes
  file:
    path: /etc/consul
    state: directory
    mode: 0770
  tags:
    - consul
    - distributive
    - consul-template

- name: create symlink to distributive consul-template checklist
  sudo: yes
  file:
    state: link
    src: /usr/share/distributive/consul-template.json
    dest: /etc/distributive.d/consul-template.json
  tags:
    - consul
    - distributive
    - consul-template

- name: register distributive tests with consul
  sudo: yes
  copy:
    src: distributive-consul-template-check.json
    dest: /etc/consul/
  notify:
    - reload consul
  tags:
    - consul
    - distributive
    - consul-template
