---
- name: generate registrator systemd service file 
  sudo: yes
  template:
    src: registrator.service.j2 
    dest: "/usr/lib/systemd/system/{{ registrator_service }}.service"
  notify: relaod systemd daemon
  register: registrator_unit
  tags: 
    - registrator
    - registrator-docker-create-systemd-sevice

- name: register registrator service with systemd
  sudo: yes
  service: 
    enabled: yes
    name: "{{ registrator_service }}" 
    state: started
  tags: 
    - registrator 
    - registrator-docker-systemd-start
