---
- name: set timezone to etc/utc
  sudo: yes
  file: >
    src=/usr/share/zoneinfo/Etc/UTC
    dest=/etc/localtime
    state=link
    force=yes

- name: setup latest centos and epel-release repos
  sudo: yes
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - centos-release
    - epel-release

- name: enable centos-fasttrack repo
  sudo: yes
  ini_file: >
    dest=/etc/yum.repos.d/CentOS-fasttrack.repo
    section=fasttrack
    option=enabled
    value=1
