---
# default set to Etc/UTC with CentOS 7 image build 20141129 [http://cloud.centos.org/centos/7/images/]
- name: set timezone to etc/utc
  sudo: yes
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: yes

- name: enable epel-release repo
  sudo: yes
  yum:
    name: epel-release
    state: latest
