- name: Calico directory for cni config
  sudo: yes
  file:
    path: /etc/kubernetes/cni
    state: directory
  tags:
    - calico

- name: Calico cni config for kubernetes
  sudo: yes
  template:
    src: calico-plugin.conf
    dest: /etc/kubernetes/cni/10-calico.conf
  tags:
    - calico
