---
- name: install dnsmasq and bind-utils
  sudo: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - dnsmasq
    - bind-utils
  tags:
    - package
    - dnsmasq

- name: configure consul lookups
  sudo: yes
  copy: 
    content: 'server=/consul/127.0.0.1#8600'
    dest: /etc/dnsmasq.d/10-consul
  notify:
    - restart dnsmasq
  tags:
    - dnsmasq

- name: set localhost as nameserver
  sudo: yes
  lineinfile:
    dest: /etc/resolv.conf
    line: "nameserver 127.0.0.1"
    insertbefore: "^nameserver"
  tags:
    - dnsmasq
