---
- name: install wget
  yum: name=wget state=latest

- name: get netplugin and netmaster
  script: getcontiv.sh
  register: getcontivOutput

- set_fact:
  contiv_bin_path: {{ getcontivOutput.stdout }}/contiv_bin

- name: copy netmaster exec file
  copy: src={{ contiv_bin_path }}/netmaster dest=/usr/bin/netmaster mode=0755

- name: copy netctl exec file
  copy: src={{ contiv_bin_path }}/netctl dest=/usr/bin/netctl mode=0755

- name: copy netmaster setup script
  copy: src=nw_setup.sh dest=/usr/bin/nw_setup.sh mode=0755

- name: copy environment file for netmaster
  copy: src=netmaster.env dest=/etc/default/netmaster

- name: copy systemd units for netmaster
  copy: src=netmaster.service dest=/etc/systemd/system/netmaster.service

- name: setup netmaster host alias
  lineinfile: regexp=.*netmaster$ dest=/etc/hosts line="{{ contiv_service_vip }} netmaster"

- name: wait for netmaster
  action: shell netctl tenant ls
  register: netctl_res
  until: netctl_res.stdout.find("default") != -1
  retries: 7
  delay: 10

- include: aci.yml
  when: contiv_fabric_mode == "aci"

#Creates default nw and EPG
- name: configure network
  shell: nw_setup.sh
