---
- name: install docker
  sudo: yes
  yum:
    name: docker
    state: present

- name: configure docker consul dns
  sudo: yes
  lineinfile:
    dest: /etc/sysconfig/docker 
    regexp: ^OPTIONS
    line: OPTIONS=--selinux-enabled -H fd:// --dns {{ ansible_default_ipv4.address }}  --dns-search service.consul
    state: present

- name: enable docker
  sudo: yes
  service:
    name: docker
    enabled: yes
    state: started
