---
# Workaround for https://github.com/CiscoCloud/microservices-infrastructure/issues/161 
- name: install latest device-mapper-libs
  sudo: yes
  yum:
    name: device-mapper-libs
    state: latest
  tags:
    - docker
    - bootstrap

- name: install docker repo
  sudo: yes
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo
  tags:
    - docker
    - bootstrap

- name: install docker
  sudo: yes
  yum:
    name: docker-engine-1.7.1
    state: present
  tags:
    - docker
    - bootstrap

- name: configure docker consul dns
  sudo: yes
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: ^other_args=
    line: other_args='--dns {{ private_ipv4 }} --dns-search service.{{ consul_dns_domain }}'
    state: present
  notify:
    - restart docker
  tags:
    - docker

- name: enable docker
  sudo: yes
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker
    - bootstrap # needed to install Docker images during bootstrap

- include: collectd.yml 
