---
- name: install docker
  sudo: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker

- name: enable docker
  sudo: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: add {{ ansible_ssh_user }} to docker group
  sudo: yes
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes
