---
- name: enable centos-virt7-testing repo
  sudo: yes
  copy: >
    src=CentOS-virt7-testing.repo
    dest=/etc/yum.repos.d/CentOS-virt7-testing.repo
    owner=root
    group=root
    mode=0644

- name: install docker and python-docker-py
  sudo: yes
  yum: >
    name={{ item }}
    state=latest
  with_items:
   - docker
   - python-docker-py
  notify:
   - restart docker 

- name: enable docker
  sudo: yes
  service: >
    name=docker
    state=started
    enabled=yes

- name: add {{ ansible_ssh_user }} to docker group
  sudo: yes
  user: >
    name={{ ansible_ssh_user }}
    groups=docker
    append=yes
