---
marathon_http_credentials: ""
marathon_keystore_path: ""
marathon_keystore_password: ""

# framework authentication
marathon_principal: marathon
marathon_secret: ""

# register serivce with consul
consul_bin: /bin/consul
consul_dir: /etc/consul
