---
- include: skydns.yml
  when: dns_setup
  tags:
    - kubernetes

- include: dashboard.yml
  when: enable_ui
  tags:
    - kubernetes

- include: logging.yml
  when: enable_logging
  tags:
    - kubernetes

- include: monitoring.yml
  when: enable_monitoring
  tags:
    - kubernetes
