---
users:
  - name: kechambe
    enable: 1
    pubkeys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCz2jBBcHTOayH0vHIDIn6ifiy9RyxkzxY9osINSkhNUZTKqcy7YNfgWT9A1XlyxjMv0oj767KzohO3nnBly+di63+33wF78SEILo9HRiPcERXHPKrlqTEy3ONgJr0HSwmPODtqtCc9kqknTyR8LXsZwtTB80rCFKZrh7ty04gy8EtKVNSceqRML2SHDfXKeXRtDjINWJYr8L/wcqq7Zoc7z+dFlI4a1zV3lax+mckZdkwQPaWCHOdSxy3gz58Spw72AHVjk0fvi/BU1iDJKcMO35a7VLjFXR56cbJNFLQPJBrbMKSyWa06u++YoRvRjWHHHW8bpkj0k4ZLybebR4a9
  - name: sborrell
    enable: 1
    pubkeys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVuF6qHWJ3ohZ4OCHMwnYv/raB3k6NUgo15rm19vH7peQw0GyAIwhXdVs+XWVJUEri9eYhFEtyHbWPXxDi5mXJQgupPB2WrknPWFutqynil4I7oZ5yE21L/RNef7teklx+2DbJBBQbnp9WYO07mC+7uMPIl1GPkdtbi9CDHEa7CfHlJVS/HeThvHClC3AqqCahHPbBE4No54qZsqbwGDaXLWpISvgXgJBzjMSjWZFTP5NvIVugEW3kSvvU6ytqf0BWFKDfZOrIFmdl4M0mxO+eTNT7J7vTO2STooXcjEj9d7mV3BfXPSeePwDw/RFtieYxJ6pVUqO9Qmstf0jFySvl

  - name: brhicks
    enable: 1
    pubkeys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDN8C6JTHtODnYM++s5yWeacHFTH1Wa+n9OfKpmT30ULNGS1QflrkeJ4TN4JUd7OSa82ZuW4JPA5/30+bwXNrUchwMk4V8aMSrFjCWtf3c5l0a0c8uWW7AOwIZVOQ0/g3E84xay/yF/kiSqWwVluB6sC7PUosUgc4XPAi6Errt5fl3G9I/pTQozD+kvmvdAwDG2J99JGmy6oTUsj78gSD3wQNiY/qBn2mXWwCDZuigQ+PPf4K2+7cYD4Y+9pWAyjlNRd5a9ZR/ZIYOXCnCjS2bVcxhW1w+pT//Vk8VMNDpuHyHZIrU3RtZ+LmX/6Z0wPzn9qJ11jiSF4ibGXBV/JZpv

  - name: caubucho
    enable: 1
    pubkeys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKptmKAMk+5tKYCmfz7VD1YXzBSjnjcvc3BKEhbXqhgOPdIvyTgMd6N95BukadWbVfHfy9NGIBB/36b/gP1l9Vw7DTW7RLnyVOjTitbHG87EUppjB7N1YL0sgJ3Fr0y7ON10lIdZBT2vkyAsXmFwShnRRvkFLr5l4LaYAI2pnx/C612s2MwGbZORpOVY23ozKdaQjP70K2AuXKQmFFKnofKiBLFNheE5r8yjbPqqDhpLAC8kCIG0Gosd5uNuk1N2Y/QjXivbDWMVsnCECQN+NVWYR2/4m5BFDW5DHbMzLGxbttWF65jgZnM0CuD+pln8WwYc1QPTKFMz8LE9luZwe1 Chris.Aubuchon@gmail.com 
  
  - name: npateriy
    enable: 1
    pubkeys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC59mnYFY58WFbVytaV0ktZlSlteSecPCCG4vWEoukcaU+0RnG1nyMpUhnjDKMHOzL3xtHtMCqC/PLxEDfhAw8Y8Dg26PsVFVE7X8ZC3dZBMomwXMScl3qVD0F3oixcu8AFxNzJ/4Pb0X/82iwv4DWLGdncnx22qIdThsQNg3zQfPN+sUkgpVzqtYDlZQV0PFR6/DvCdtFhj2vzWQ4LCqD+vTz2l2baNutwjQwwCUfP3IeS/58oiwaJ9FT+5HR4O3LGPX2wPm4ZI9hN2pqF3sPUEETjwUtZXey1BsZZctVJA0hRW41K6ByaUchzNhgf5V4VsCLeeUU8SbU138FeWvJl npateriy@cisco.com

