---
- hosts: consul_servers
  tasks:
  - name: get consul wan gossip pool members
    shell: docker exec consul consul members -wan | grep -q {{ ansible_eth0.ipv4.address }}:8302
    register: result
    changed_when: result.rc != 0
    failed_when: no

  - name: join consul wan gossip pool
    command: docker exec consul consul join -wan {{ consul_join_wan }}
    when: result|changed
