---
- hosts: localhost
  connection: local
  vars:
    - base_url: http://buildlogs.centos.org/rolling/7/
    - image: CentOS-7-x86_64-GenericCloud-20141029_01
    - sha256sum: ea37e583c25927e98c1b75432be72b1bda9b8891b478d32849d2ef3467f24c3
    - tmp_dir: "{{ ansible_env.PWD }}"/tmp
  tasks:
    - name: enable epel repo
      sudo: yes
      yum: >
        name=epel-release
        state=latest
        
    - name: enable openstack repo
      sudo: yes
      yum: >
        name=https://repos.fedorapeople.org/repos/openstack/openstack-icehouse/rdo-release-icehouse-4.noarch.rpm
        state=present

    - name: install qemu-img and python-glanceclient
      sudo: yes
      yum: >
        name={{ item }}
        state=latest
      with_items:
        - qemu-img
        - python-glanceclient

    - name: create tmp directory
      file: >
        path={{ tmp_dir }}
        state=directory

    - name: download image from url
      get_url: >
        url={{ base_url }}/{{ image }}.qcow2
        dest={{ tmp_dir }}/{{ image }}.qcow2
        sha256sum={{ sha256sum }}

    - name: convert image from qcow2 to raw
      command: >
        qemu-img convert
        {{ tmp_dir }}/{{ image }}.qcow2
        {{ tmp_dir }}/{{ image }}.raw
        creates={{ tmp_dir }}/{{ image }}.raw

    - name: upload image to glance
      glance_image: >
        auth_url={{ lookup('env','OS_AUTH_URL') }}
        login_username={{ lookup('env','OS_USERNAME') }}
        login_password={{ lookup('env','OS_PASSWORD') }}
        login_tenant_name={{ lookup('env','OS_TENANT_NAME') }}
        name={{ image }}
        file={{ tmp_dir }}/{{ image }}.raw
        disk_format=raw
        is_public=false
        state=present
