---
- include: provision-hosts.yml

- hosts:  all
  gather_facts: no
  tasks:

  - name: reboot host
    sudo: yes
    shell: nohup bash -c "sleep 2s && reboot" &
    register: reboot

  - name: wait for host boot
    local_action:
      module: wait_for
      host: "{{ ansible_ssh_host }}"
      port: 22
      delay: "{{ boot_wait | default(60) }}"
      timeout: 120
      state: started
