---
- include: provision-hosts.yml

- hosts: localhost
  gather_facts: no
  tasks:
    - name: create local directory for package manifests
      file:
        path: /tmp/packages
        state: directory

- hosts: all
  tasks:
    - name: get list of installed packages
      shell: rpm -qa | sort -V
      register: packages
      changed_when: no

    - name: print package manifest
      debug:
        msg: "{{ packages.stdout_lines }}"

    - name: write package manifest to local host
      local_action:
        module: copy
        content: "{{ packages.stdout }}"
        dest: "/tmp/packages/{{ ansible_eth0.ipv4.address }}-package.log"
